#!/usr/bin/python
# Print /etf/fstab getting the fields as close to their intended columns as may
# be.  Long fields push the remainder of the line over as little as is possible
# so that the columns come nearer to alignment.

import	os
import	sys

class   FstabPrettyprint( object ):

    def __init__( self ):
        return

    def pad(self, parts, cols):
        s = ""
        while len(parts) > 0:
            c = cols.pop(0)
            l = len(s)
            n = c - l
            if n < 1 and c > 0: n = 1
            s = s + " " * n + parts.pop(0)
        return s

    def process( self, f = sys.stdin, out = sys.stdout ):
        for line in f:
            line = line.strip()
            if not line.startswith( '#' ):
                parts = line.split()
                l = len(parts)
                # Reformat only regular, or bind-mount, lines
                if l == 4 or l == 6:
                    #
                    opts = parts[3].split(',')
                    opts.sort()
                    parts[3]  = ",".join(opts)
                    #
                    line = self.pad(parts,[
                        0, 24, 47, 55, 77, 79
                    ])
            print >>out, line
        return

    def do_file( self, fn, out = sys.stdout ):
        try:
            f = open( fn, 'rt' )
        except Exception, e:
            print >>sys.stderr, 'Cannot open "%s" for reading.' % fn
            raise e
        self.process( f, out )
        f.close()
        return


if __name__ == '__main__':
    pp = FstabPrettyprint()
    argc = len(sys.argv)
    if argc == 1:
        pp.process()
    else:
        for optarg in sys.argv[1:]:
            if optarg == '-':
                pp.process()
            else:
                pp.do_file( optarg )
    sys.exit( 0 )
